// Checking the declaration, against AMC's own answers.
//
// The sequence computes everything from what the operator declares, so a
// declaration that is merely plausible produces a directory that is
// confidently wrong -- cell voltages out of order drive the battery failsafes
// to thresholds that trip on a full pack.
//
// The expectations here are not written from reading AMC's Python. They are
// generated by running it (scripts/gen_validation_fixtures.py), because
// transcribing a rule and then testing it against what I believed the rule
// was proves only that I was consistent with myself.

import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { test } from 'node:test'

import {
  cellVoltagesFor,
  declarationFrom,
  validateDeclaration,
  validateEntryLimit,
  validateMotorPoles
} from '../packages/amc-steps/dist/index.js'

const golden = JSON.parse(
  readFileSync(fileURLToPath(new URL('./fixtures/validation.json', import.meta.url)), 'utf8')
)
const tables = JSON.parse(
  readFileSync(fileURLToPath(new URL('../steps/connection-tables.json', import.meta.url)), 'utf8')
)

/** The declarations the fixtures were generated against. */
const BATTERY = {
  'Battery/Specifications/Chemistry': 'Lipo',
  'Battery/Specifications/Volt per cell max': '4.2',
  'Battery/Specifications/Volt per cell arm': '3.8',
  'Battery/Specifications/Volt per cell low': '3.6',
  'Battery/Specifications/Volt per cell crit': '3.3',
  'Battery/Specifications/Volt per cell min': '3.2'
}
const FRAME = {
  'Frame/Specifications/TOW min Kg': '0.6',
  'Frame/Specifications/TOW max Kg': '1.2'
}

function validateOne(path, value) {
  const values = path[0] === 'Battery' ? BATTERY : path[0] === 'Frame' ? FRAME : {}
  const declaration = declarationFrom(values)
  const [error] = validateDeclaration([[path, value]], declaration, tables)
  return error
}

test('every entry-limit case agrees with AMC, message and correction alike', () => {
  for (const expected of golden.entry) {
    const error = validateOne(expected.path, expected.value)
    const where = `${expected.label} (${expected.path.join('>')} = ${expected.value})`

    if (expected.message === '') {
      assert.equal(error, undefined, `${where} should be accepted`)
      continue
    }

    assert.ok(error, `${where} should be rejected`)

    if (expected.message.includes('\n')) {
      // AMC pastes CPython's own conversion error in front of its sentence
      // ("could not convert string to float: 'flat'"). Reproducing an
      // interpreter's exception text would be pedantry; the sentence that
      // tells the operator what happens next is the part that matters.
      assert.ok(
        expected.message.endsWith(error.message),
        `${where}: expected AMC's message to end with ${JSON.stringify(error.message)}`
      )
    } else {
      assert.equal(error.message, expected.message, where)
    }

    // The correction, including the floating-point noise AMC's own arithmetic
    // produces -- 3.8 + 0.01 is 3.8099999999999996 in both languages, and a
    // rounded answer here would be a different number from the one AMC writes.
    assert.equal(error.suggestion ?? null, expected.suggestion, `${where}: correction`)
  }
})

test('the motor pole count must be even, as AMC says', () => {
  for (const expected of golden.poles) {
    const error = validateMotorPoles(['Motors', 'Specifications', 'Poles'], expected.value)
    assert.deepEqual(
      error ? [error.message] : [],
      expected.errors,
      `poles = ${expected.value}`
    )
  }
})

test('a port claimed twice is reported, and a shared bus is not', () => {
  for (const expected of golden.duplicates) {
    const entries = expected.entries.map(([path, value]) => [path, value])
    const errors = validateDeclaration(entries, declarationFrom({}), tables)
    assert.deepEqual(
      errors.map((error) => error.message),
      expected.errors,
      expected.label
    )
  }
})

test('every chemistry seeds the voltages AMC recommends for it', () => {
  for (const [chemistry, expected] of Object.entries(golden.chemistries)) {
    const seeded = cellVoltagesFor(tables, chemistry)
    for (const [type, voltage] of Object.entries(expected.recommended)) {
      assert.equal(seeded.get(type), voltage, `${chemistry} ${type}`)
    }
  }
})

test('the corpus covers the rules, rather than a couple of them', () => {
  // A fixture file that shrank to nothing would let every assertion above pass.
  assert.ok(golden.entry.length >= 25, `only ${golden.entry.length} entry cases`)
  assert.ok(golden.entry.filter((entry) => entry.message !== '').length >= 15)
  assert.equal(Object.keys(golden.chemistries).length, 8)
})

test('a limit that only one end of a pair breaks is reported on that end', () => {
  // Both weights present and consistent: nothing to say about either.
  const declaration = declarationFrom(FRAME)
  assert.deepEqual(
    validateDeclaration(
      [
        [['Frame', 'Specifications', 'TOW min Kg'], '0.6'],
        [['Frame', 'Specifications', 'TOW max Kg'], '1.2']
      ],
      declaration,
      tables
    ),
    []
  )
})

test('a value outside its field\'s choices stops the other checks', () => {
  // AMC continues past a bad combobox value rather than also complaining that
  // it is not a number, which would be two errors about one mistake.
  const errors = validateDeclaration(
    [[['Motors', 'Specifications', 'Poles'], 'Quad']],
    declarationFrom({}),
    tables,
    { choices: (path) => (path[2] === 'Poles' ? ['14', '28'] : undefined) }
  )
  assert.equal(errors.length, 1)
  assert.match(errors[0].message, /Allowed values are: 14, 28/)
})

test('an empty declaration has nothing wrong with it', () => {
  assert.deepEqual(validateDeclaration([], declarationFrom({}), tables), [])
})

test('a field nobody has answered yet is not evidence against its neighbour', () => {
  // The one deliberate divergence from AMC. AMC opens a template before it
  // validates, so the value it compares against is always there; a missing one
  // reaches validate_against_another_value as an empty dict and is reported as
  // "not a float nor string". This form starts empty, and that message against
  // every neighbour of every unanswered field would bury the real ones.
  const errors = validateDeclaration(
    [[['Battery', 'Specifications', 'Volt per cell arm'], '3.8']],
    declarationFrom({ 'Battery/Specifications/Chemistry': 'Lipo' }),
    tables
  )
  assert.deepEqual(errors, [])

  // The chemistry limits still apply, because those do not need a neighbour.
  const [tooHigh] = validateDeclaration(
    [[['Battery', 'Specifications', 'Volt per cell arm'], '4.9']],
    declarationFrom({ 'Battery/Specifications/Chemistry': 'Lipo' }),
    tables
  )
  assert.match(tooHigh.message, /above the Lipo maximum limit of 4.2/)
})
